/* Generated By:JavaCC: Do not edit this line. VhdlParserCoreConstants.java */
package net.sourceforge.veditor.parser;

public interface VhdlParserCoreConstants {

  int EOF = 0;
  int MULTI_LINE_COMMENT = 2;
  int SINGLE_LINE_COMMENT = 9;
  int LIBRARY = 10;
  int BODY = 11;
  int PACKAGE = 12;
  int USE = 13;
  int ENTITY = 14;
  int ARCHITECTURE = 15;
  int IS = 16;
  int OF = 17;
  int RECORD = 18;
  int GENERIC = 19;
  int PORT = 20;
  int PROCESS = 21;
  int BEGIN = 22;
  int END = 23;
  int CONSTANT = 24;
  int PROCEDURE = 25;
  int FUNCTION = 26;
  int SIGNAL = 27;
  int SHARED = 28;
  int VARIABLE = 29;
  int TYPE = 30;
  int SUBTYPE = 31;
  int FILE = 32;
  int ALIAS = 33;
  int ATTRIBUTE = 34;
  int COMPONENT = 35;
  int FOR = 36;
  int IF = 37;
  int CASE = 38;
  int LOOP = 39;
  int RETURN = 40;
  int DISCONNECT = 41;
  int GROUP = 42;
  int BLOCK = 43;
  int ASSERT = 44;
  int GENERATE = 45;
  int TO = 46;
  int RANGE = 47;
  int WITH = 48;
  int MODE = 49;
  int LPAREN = 50;
  int RPAREN = 51;
  int LBRACE = 52;
  int RBRACE = 53;
  int LBRACKET = 54;
  int RBRACKET = 55;
  int EOS = 56;
  int PARA = 57;
  int AT = 58;
  int BQ = 59;
  int DOLLAR = 60;
  int COMMA = 61;
  int COLON = 62;
  int ASSIGN = 63;
  int EQUAL = 64;
  int IDENT = 65;
  int SPC_CHAR = 66;
  int OTHER = 67;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 3>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"library\"",
    "\"body\"",
    "\"package\"",
    "\"use\"",
    "\"entity\"",
    "\"architecture\"",
    "\"is\"",
    "\"of\"",
    "\"record\"",
    "\"generic\"",
    "\"port\"",
    "\"process\"",
    "\"begin\"",
    "\"end\"",
    "\"constant\"",
    "\"procedure\"",
    "\"function\"",
    "\"signal\"",
    "\"shared\"",
    "\"variable\"",
    "\"type\"",
    "\"subtype\"",
    "\"file\"",
    "\"alias\"",
    "\"attribute\"",
    "\"component\"",
    "\"for\"",
    "\"if\"",
    "\"case\"",
    "\"loop\"",
    "\"return\"",
    "\"disconnect\"",
    "\"group\"",
    "\"block\"",
    "\"assert\"",
    "\"generate\"",
    "\"to\"",
    "\"range\"",
    "\"with\"",
    "<MODE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"#\"",
    "\"@\"",
    "\"`\"",
    "\"$\"",
    "\",\"",
    "\":\"",
    "\"<=\"",
    "\"=\"",
    "<IDENT>",
    "<SPC_CHAR>",
    "\"[.]\"",
  };

}
