/* Generated By:JavaCC: Do not edit this line. VerilogParserCoreTokenManager.java */
package net.sourceforge.veditor.parser.verilog;

/** Token Manager. */
public class VerilogParserCoreTokenManager implements VerilogParserCoreConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x2L) != 0L || (active1 & 0x8000000000L) != 0L)
            return 3;
         if ((active0 & 0x2400000000000L) != 0L)
         {
            jjmatchedKind = 119;
            return 90;
         }
         if ((active1 & 0x200L) != 0L)
            return 0;
         if ((active0 & 0x280220004000000L) != 0L)
         {
            jjmatchedKind = 119;
            return 149;
         }
         if ((active0 & 0x100000200000000L) != 0L)
         {
            jjmatchedKind = 119;
            return 194;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 119;
            return 137;
         }
         if ((active0 & 0x5c6499fde3776000L) != 0L)
         {
            jjmatchedKind = 119;
            return 8;
         }
         if ((active0 & 0x40008800000L) != 0L)
         {
            jjmatchedKind = 119;
            return 242;
         }
         if ((active1 & 0x40000L) != 0L)
            return 12;
         if ((active0 & 0x2010000000000000L) != 0L)
         {
            jjmatchedKind = 119;
            return 62;
         }
         if ((active0 & 0x1000000080000L) != 0L)
         {
            jjmatchedKind = 119;
            return 223;
         }
         return -1;
      case 1:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 1;
            }
            return 61;
         }
         if ((active0 & 0x800000000200000L) != 0L)
            return 8;
         if ((active0 & 0x8000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 1;
            }
            return 241;
         }
         if ((active0 & 0x77e7ffffe7dfe000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 1;
            }
            return 8;
         }
         return -1;
      case 2:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 2;
            }
            return 60;
         }
         if ((active0 & 0x44021543134000L) != 0L)
            return 8;
         if ((active0 & 0x77a3fdeaaccca000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 2;
            }
            return 8;
         }
         return -1;
      case 3:
         if ((active0 & 0x300240208460000L) != 0L)
            return 8;
         if ((active0 & 0x74f7d9fde698e000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 3;
            }
            return 8;
         }
         return -1;
      case 4:
         if ((active0 & 0x4008a000808000L) != 0L)
            return 8;
         if ((active0 & 0x76b7d15de6186000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 4;
            return 8;
         }
         return -1;
      case 5:
         if ((active0 & 0x2011104004002000L) != 0L)
            return 8;
         if ((active0 & 0x56a6c11de2184000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 5;
            return 8;
         }
         return -1;
      case 6:
         if ((active0 & 0x626c01980104000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 6;
            return 8;
         }
         if ((active0 & 0x5080010462080000L) != 0L)
            return 8;
         return -1;
      case 7:
         if ((active0 & 0x4c01100104000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 7;
            return 8;
         }
         if ((active0 & 0x622000880000000L) != 0L)
            return 8;
         return -1;
      case 8:
         if ((active0 & 0x4801100100000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 8;
            return 8;
         }
         if ((active0 & 0x400000004000L) != 0L)
            return 8;
         return -1;
      case 9:
         if ((active0 & 0x4001100000000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 9;
            return 8;
         }
         if ((active0 & 0x800000100000L) != 0L)
            return 8;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 88;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000200000000L, 0x0L);
      case 35:
         return jjStopAtPos(0, 80);
      case 36:
         return jjStartNfaWithStates_0(0, 82, 12);
      case 37:
         return jjStopAtPos(0, 107);
      case 38:
         jjmatchedKind = 104;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000L, 0x0L);
      case 40:
         return jjStartNfaWithStates_0(0, 73, 0);
      case 41:
         return jjStopAtPos(0, 74);
      case 42:
         jjmatchedKind = 102;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000000000L, 0x0L);
      case 43:
         jjmatchedKind = 100;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000L, 0x0L);
      case 44:
         return jjStopAtPos(0, 83);
      case 45:
         jjmatchedKind = 101;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000L, 0x8L);
      case 46:
         return jjStopAtPos(0, 84);
      case 47:
         jjmatchedKind = 103;
         return jjMoveStringLiteralDfa1_0(0x2L, 0x0L, 0x0L);
      case 58:
         return jjStopAtPos(0, 91);
      case 59:
         return jjStopAtPos(0, 79);
      case 60:
         jjmatchedKind = 87;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20100080000000L, 0x0L);
      case 61:
         jjmatchedKind = 85;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000040000000L, 0x0L);
      case 62:
         jjmatchedKind = 86;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40200100000000L, 0x0L);
      case 63:
         return jjStopAtPos(0, 90);
      case 64:
         return jjStopAtPos(0, 81);
      case 91:
         return jjStopAtPos(0, 77);
      case 93:
         return jjStopAtPos(0, 78);
      case 94:
         jjmatchedKind = 106;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000000000L, 0x0L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x2010000000000000L, 0x0L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x8000L, 0x0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1420000020000000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4081540514000L, 0x0L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x40000083020000L, 0x0L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x100800000000L, 0x0L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x400001a000200000L, 0x0L, 0x0L);
      case 106:
         return jjMoveStringLiteralDfa1_0(0x40000L, 0x0L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x0L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800004000000000L, 0x0L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x2400000000000L, 0x0L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x280220004000000L, 0x0L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1000000080000L, 0x0L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x100000200000000L, 0x0L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x40008800000L, 0x0L, 0x0L);
      case 123:
         return jjStopAtPos(0, 75);
      case 124:
         jjmatchedKind = 105;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 76);
      case 126:
         jjmatchedKind = 89;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1c00000000000L, 0x0L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 99);
         else if ((active1 & 0x400000000000L) != 0L)
            return jjStopAtPos(1, 110);
         break;
      case 42:
         if ((active0 & 0x2L) != 0L)
            return jjStopAtPos(1, 1);
         else if ((active1 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 116);
         break;
      case 58:
         if ((active1 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 92);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 93);
         break;
      case 60:
         if ((active1 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 108;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20000000000000L, active2, 0L);
      case 61:
         if ((active1 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 95);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 96);
         else if ((active1 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xc000000000000L, active2, 0L);
      case 62:
         if ((active1 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x8L) != 0L)
            return jjStopAtPos(1, 131);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000000000L, active2, 0L);
      case 94:
         if ((active1 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 112);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x400208000000L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x6a0320824008000L, active1, 0L, active2, 0L);
      case 102:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(1, 21, 8);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1101040000000000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000400000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x400401b540114000L, active1, 0L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x40800003062000L, active1, 0L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L, active1, 0L, active2, 0L);
      case 114:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 59, 8);
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000L, active1, 0L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x4080000000L, active1, 0L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L, active2, 0L);
      case 124:
         if ((active1 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 98);
         else if ((active1 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 111);
         break;
      case 126:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 113);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 60:
         if ((active1 & 0x20000000000000L) != 0L)
            return jjStopAtPos(2, 117);
         break;
      case 61:
         if ((active1 & 0x4000000000000L) != 0L)
            return jjStopAtPos(2, 114);
         else if ((active1 & 0x8000000000000L) != 0L)
            return jjStopAtPos(2, 115);
         break;
      case 62:
         if ((active1 & 0x40000000000000L) != 0L)
            return jjStopAtPos(2, 118);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x220200000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L, active1, 0L);
      case 100:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x4001540106000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000080000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000020000000L, active1, 0L);
      case 103:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 41, 8);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000008000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000008840000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x100880000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x2008000000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x2004000000L, active1, 0L);
      case 114:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40440002020000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x1010000200400000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x14000000000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x3000c00020000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000c0080000L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 8);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 8);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 56, 8);
         return jjMoveStringLiteralDfa4_0(active0, 0x80010806000000L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000008000L);
      case 107:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 8);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 8);
         break;
      case 108:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000800000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 110:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 8);
         return jjMoveStringLiteralDfa4_0(active0, 0x1080000000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x406004000000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000100000L);
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 27, 8);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000400000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0xa000002000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x480100444000000L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000000L);
      case 101:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 8);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 54, 8);
         return jjMoveStringLiteralDfa5_0(active0, 0x3001000000000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x10010000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000080000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000002000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 110:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 8);
         break;
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000800000000L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000000L);
      case 116:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 8);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 8);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 43, 8);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000080000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4120000000L);
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000800000000L);
      case 100:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 101:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x410002100000L);
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x220000080000000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000020000000L);
      case 110:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 52, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x1100000000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L);
      case 114:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 44, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x402000000000000L);
      case 115:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000440000000L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 8);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x400800000000000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x100100000L);
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 8);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 55, 8);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 8);
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000000L);
      case 107:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(6, 34, 8);
         break;
      case 108:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 62, 8);
         break;
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000L);
      case 114:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 8);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 40, 8);
         break;
      case 116:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(6, 29, 8);
         return jjMoveStringLiteralDfa7_0(active0, 0x2400800000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 121:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(7, 35, 8);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 57, 8);
         return jjMoveStringLiteralDfa8_0(active0, 0x4400000000000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 109:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 58, 8);
         break;
      case 110:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 31, 8);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 53, 8);
         break;
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x801000000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L);
      case 121:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 49, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x801000000000L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(8, 14, 8);
         break;
      case 102:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000L);
      case 114:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 46, 8);
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 109:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 47, 8);
         break;
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x4001000000000L);
      case 121:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(9, 20, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 36, 8);
         break;
      case 110:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(10, 32, 8);
         break;
      case 121:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 50, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 250;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 194:
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 12);
                  else if (curChar == 39)
                     jjCheckNAddStates(13, 20);
                  else if (curChar == 34)
                     jjCheckNAddStates(21, 23);
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(14);
                  }
                  break;
               case 149:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 137:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 242:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 223:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 241:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 0:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0xfffffdffffffffffL & l) != 0L && kind > 4)
                     kind = 4;
                  break;
               case 3:
                  if (curChar != 47)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(4);
                  break;
               case 5:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 10:
                  if ((0xfffffffeffffffffL & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 11:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(14);
                  break;
               case 15:
                  if (curChar == 34)
                     jjCheckNAddStates(21, 23);
                  break;
               case 16:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 18:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 19:
                  if (curChar == 34 && kind > 130)
                     kind = 130;
                  break;
               case 20:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(24, 27);
                  break;
               case 21:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 22:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 24:
                  if (curChar == 39)
                     jjCheckNAddStates(13, 20);
                  break;
               case 27:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAddTwoStates(27, 28);
                  break;
               case 28:
                  if ((0x83ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(28);
                  break;
               case 31:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 32:
                  if ((0x83ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(32);
                  break;
               case 35:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAddTwoStates(35, 36);
                  break;
               case 36:
                  if ((0x80ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(36);
                  break;
               case 39:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if ((0x8003000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(40);
                  break;
               case 47:
                  if (curChar == 48 && kind > 66)
                     kind = 66;
                  break;
               case 52:
                  if (curChar == 49 && kind > 66)
                     kind = 66;
                  break;
               case 123:
                  if (curChar == 48 && kind > 69)
                     kind = 69;
                  break;
               case 128:
                  if (curChar == 49 && kind > 69)
                     kind = 69;
                  break;
               case 160:
                  if (curChar == 48 && kind > 72)
                     kind = 72;
                  break;
               case 167:
                  if (curChar == 49 && kind > 72)
                     kind = 72;
                  break;
               case 174:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 12);
                  break;
               case 175:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(175, 176);
                  break;
               case 176:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 177:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(177, 178);
                  break;
               case 178:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(29, 30);
                  break;
               case 179:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(179, 180);
                  break;
               case 180:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 181:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(181, 182);
                  break;
               case 182:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(37, 38);
                  break;
               case 183:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(183, 184);
                  break;
               case 184:
                  if (curChar != 46)
                     break;
                  if (kind > 129)
                     kind = 129;
                  jjCheckNAdd(185);
                  break;
               case 185:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 129)
                     kind = 129;
                  jjCheckNAdd(185);
                  break;
               case 186:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(28, 30);
                  break;
               case 187:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(188, 189);
                  break;
               case 188:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(188, 189);
                  break;
               case 190:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(191);
                  break;
               case 191:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 129)
                     kind = 129;
                  jjCheckNAdd(191);
                  break;
               case 195:
                  if (curChar == 49 && kind > 65)
                     kind = 65;
                  break;
               case 203:
                  if (curChar == 48 && kind > 65)
                     kind = 65;
                  break;
               case 218:
                  if (curChar == 48 && kind > 64)
                     kind = 64;
                  break;
               case 224:
                  if (curChar == 49 && kind > 64)
                     kind = 64;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 194:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 215;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 210;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 208;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 204;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 201;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 196;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 62:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 110)
                     jjCheckNAdd(63);
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 2:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  else if (curChar == 92)
                     jjCheckNAdd(10);
                  else if (curChar == 96)
                     jjstateSet[jjnewStateCnt++] = 7;
                  if (curChar == 119)
                     jjAddStates(31, 34);
                  else if (curChar == 115)
                     jjAddStates(35, 38);
                  else if (curChar == 116)
                     jjAddStates(39, 45);
                  else if (curChar == 114)
                     jjAddStates(46, 51);
                  else if (curChar == 98)
                     jjAddStates(52, 54);
                  else if (curChar == 110)
                     jjAddStates(55, 61);
                  else if (curChar == 112)
                     jjAddStates(62, 67);
                  else if (curChar == 99)
                     jjAddStates(68, 72);
                  else if (curChar == 97)
                     jjAddStates(73, 74);
                  else if (curChar == 104)
                     jjAddStates(75, 76);
                  else if (curChar == 120)
                     jjAddStates(77, 78);
                  else if (curChar == 95)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(14);
                  }
                  break;
               case 149:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 172;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 154;
                  else if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 151;
                  else if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 148;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 165;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 137:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 144;
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 140;
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 242:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 248;
                  else if (curChar == 111)
                     jjCheckNAdd(206);
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 241;
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 223:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 238;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 228;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 233;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 61:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 241:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 110)
                     jjCheckNAdd(198);
                  break;
               case 90:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 110;
                  else if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 98;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 89;
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 103;
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 95;
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 60:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(8);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 1:
                  if (kind > 4)
                     kind = 4;
                  break;
               case 4:
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 96)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(8);
                  break;
               case 9:
                  if (curChar == 92)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(10);
                  break;
               case 12:
               case 13:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  jjCheckNAdd(13);
                  break;
               case 14:
                  if (curChar != 95)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(14);
                  break;
               case 16:
                  jjCheckNAddStates(21, 23);
                  break;
               case 17:
                  if (curChar == 92)
                     jjAddStates(79, 81);
                  break;
               case 18:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 25:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x1000000010L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAddTwoStates(27, 28);
                  break;
               case 28:
                  if ((0x500000085000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(28);
                  break;
               case 29:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x10000000100L & l) != 0L)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 32:
                  if ((0x500007e8500007eL & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(32);
                  break;
               case 33:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x800000008000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAddTwoStates(35, 36);
                  break;
               case 36:
                  if ((0x500000085000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(36);
                  break;
               case 37:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x400000004L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if ((0x500000085000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(40);
                  break;
               case 41:
                  if (curChar == 120)
                     jjAddStates(77, 78);
                  break;
               case 42:
                  if (curChar == 114 && kind > 67)
                     kind = 67;
                  break;
               case 43:
               case 44:
               case 120:
                  if (curChar == 111)
                     jjCheckNAdd(42);
                  break;
               case 45:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 104)
                     jjAddStates(75, 76);
                  break;
               case 48:
                  if (curChar == 122)
                     jjCheckNAdd(47);
                  break;
               case 49:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 53:
                  if (curChar == 122)
                     jjCheckNAdd(52);
                  break;
               case 54:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 97)
                     jjAddStates(73, 74);
                  break;
               case 58:
                  if (curChar == 116 && kind > 51)
                     kind = 51;
                  break;
               case 59:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 63:
                  if (curChar == 100 && kind > 67)
                     kind = 67;
                  break;
               case 64:
               case 118:
                  if (curChar == 110)
                     jjCheckNAdd(63);
                  break;
               case 65:
                  if (curChar == 99)
                     jjAddStates(68, 72);
                  break;
               case 66:
                  if (curChar == 101 && kind > 28)
                     kind = 28;
                  break;
               case 67:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 120 && kind > 28)
                     kind = 28;
                  break;
               case 70:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 122 && kind > 28)
                     kind = 28;
                  break;
               case 74:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 114 && kind > 51)
                     kind = 51;
                  break;
               case 78:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 115 && kind > 71)
                     kind = 71;
                  break;
               case 82:
               case 153:
                  if (curChar == 111)
                     jjCheckNAdd(81);
                  break;
               case 83:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 112)
                     jjAddStates(62, 67);
                  break;
               case 85:
                  if (curChar == 101 && kind > 63)
                     kind = 63;
                  break;
               case 86:
               case 113:
                  if (curChar == 103)
                     jjCheckNAdd(85);
                  break;
               case 87:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 91:
                  if (curChar == 108)
                     jjCheckNAdd(47);
                  break;
               case 92:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 108)
                     jjCheckNAdd(52);
                  break;
               case 95:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 115 && kind > 69)
                     kind = 69;
                  break;
               case 98:
               case 133:
               case 147:
               case 150:
                  if (curChar == 111)
                     jjCheckNAdd(97);
                  break;
               case 99:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 112 && kind > 70)
                     kind = 70;
                  break;
               case 101:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 110 && kind > 70)
                     kind = 70;
                  break;
               case 106:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 110)
                     jjAddStates(55, 61);
                  break;
               case 114:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 119:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 121:
                  if (curChar == 116 && kind > 68)
                     kind = 68;
                  break;
               case 122:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 124:
               case 138:
                  if (curChar == 102)
                     jjCheckNAdd(123);
                  break;
               case 125:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 129:
               case 142:
                  if (curChar == 102)
                     jjCheckNAdd(128);
                  break;
               case 130:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 134:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 98)
                     jjAddStates(52, 54);
                  break;
               case 136:
                  if (curChar == 102 && kind > 68)
                     kind = 68;
                  break;
               case 139:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 143:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 114)
                     jjAddStates(46, 51);
                  break;
               case 148:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 151:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 154:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 110 && kind > 72)
                     kind = 72;
                  break;
               case 157:
               case 210:
                  if (curChar == 97)
                     jjCheckNAdd(156);
                  break;
               case 158:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 161:
               case 212:
                  if (curChar == 102)
                     jjCheckNAdd(160);
                  break;
               case 162:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 168:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 189:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(82, 83);
                  break;
               case 192:
                  if (curChar == 116)
                     jjAddStates(39, 45);
                  break;
               case 193:
                  if (curChar == 105 && kind > 65)
                     kind = 65;
                  break;
               case 196:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 100 && kind > 65)
                     kind = 65;
                  break;
               case 199:
                  if (curChar == 110)
                     jjCheckNAdd(198);
                  break;
               case 200:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 204:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 114 && kind > 65)
                     kind = 65;
                  break;
               case 207:
                  if (curChar == 111)
                     jjCheckNAdd(206);
                  break;
               case 208:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 211:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 213:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 216:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 217:
                  if (curChar == 115)
                     jjAddStates(35, 38);
                  break;
               case 219:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 225:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 103)
                     jjCheckNAdd(47);
                  break;
               case 231:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 103)
                     jjCheckNAdd(52);
                  break;
               case 236:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 119)
                     jjAddStates(31, 34);
                  break;
               case 243:
                  if (curChar == 111)
                     jjCheckNAdd(206);
                  break;
               case 244:
                  if (curChar == 107)
                     jjCheckNAdd(47);
                  break;
               case 245:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 107)
                     jjCheckNAdd(52);
                  break;
               case 248:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 4)
                     kind = 4;
                  break;
               case 4:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 10:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 16:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(21, 23);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 250 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x4L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(1, 2);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_2(0x20L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_2(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 41:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 186, 187, 189, 25, 26, 29, 
   30, 33, 34, 37, 38, 16, 17, 19, 16, 17, 21, 19, 186, 187, 189, 242, 
   243, 246, 249, 223, 229, 234, 239, 194, 197, 202, 205, 209, 211, 216, 149, 152, 
   155, 159, 166, 173, 137, 141, 145, 117, 119, 120, 122, 127, 132, 134, 90, 93, 
   96, 99, 104, 111, 68, 72, 76, 80, 83, 62, 64, 51, 56, 43, 45, 18, 
   20, 22, 190, 191, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
"\155\157\144\165\154\145", "\145\156\144\155\157\144\165\154\145", "\142\145\147\151\156", 
"\145\156\144", "\146\157\162\153", "\152\157\151\156", "\163\160\145\143\151\146\171", 
"\145\156\144\163\160\145\143\151\146\171", "\151\146", "\145\154\163\145", "\167\150\151\154\145", "\146\157\162", 
"\146\157\162\145\166\145\162", "\162\145\160\145\141\164", "\167\141\151\164", null, 
"\144\145\146\141\165\154\164", "\145\156\144\143\141\163\145", "\146\165\156\143\164\151\157\156", 
"\145\156\144\146\165\156\143\164\151\157\156", "\164\141\163\153", "\145\156\144\164\141\163\153", 
"\147\145\156\145\162\141\164\145", "\145\156\144\147\145\156\145\162\141\164\145", "\151\156\160\165\164", 
"\157\165\164\160\165\164", "\151\156\157\165\164", "\151\156\164\145\147\145\162", "\162\145\147", 
"\167\151\162\145", "\145\166\145\156\164", "\147\145\156\166\141\162", "\162\145\141\154", 
"\160\141\162\141\155\145\164\145\162", "\154\157\143\141\154\160\141\162\141\155", "\163\151\147\156\145\144", 
"\160\162\157\160\145\162\164\171", "\145\156\144\160\162\157\160\145\162\164\171", null, 
"\141\163\163\151\147\156", "\144\145\141\163\163\151\147\156", "\146\157\162\143\145", 
"\162\145\154\145\141\163\145", "\164\151\155\145", "\162\145\141\154\164\151\155\145", 
"\144\145\146\160\141\162\141\155", "\157\162", "\144\151\163\141\142\154\145", "\141\154\167\141\171\163", 
"\151\156\151\164\151\141\154", null, null, null, null, null, null, null, null, null, null, "\50", "\51", 
"\173", "\175", "\133", "\135", "\73", "\43", "\100", "\44", "\54", "\56", "\75", 
"\76", "\74", "\41", "\176", "\77", "\72", "\53\72", "\55\72", "\75\75", "\74\75", 
"\76\75", "\41\75", "\174\174", "\46\46", "\53", "\55", "\52", "\57", "\46", "\174", 
"\136", "\45", "\74\74", "\76\76", "\176\46", "\176\174", "\176\136", "\136\176", 
"\75\75\75", "\41\75\75", "\52\52", "\74\74\74", "\76\76\76", null, null, null, null, null, 
null, null, null, null, null, null, null, "\55\76", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_MULTI_LINE_COMMENT",
   "IN_PROPERTY",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, 1, 0, -1, 2, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffe001L, 0x9ffffffffffffffL, 0xeL, 
};
static final long[] jjtoSkip = {
   0x1fa4L, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x1000L, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x5aL, 0x0L, 0x0L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[250];
private final int[] jjstateSet = new int[500];
protected char curChar;
/** Constructor. */
public VerilogParserCoreTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public VerilogParserCoreTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 250; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 3)
         {
            jjmatchedKind = 3;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 6)
         {
            jjmatchedKind = 6;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
           }
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
