/* Generated By:JavaCC: Do not edit this line. VerilogParserCoreConstants.java */
package net.sourceforge.veditor.parser.verilog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VerilogParserCoreConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int PROPERTY_COMMENT = 5;
  /** RegularExpression Id. */
  int PROTECTED = 13;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 15;
  /** RegularExpression Id. */
  int MODULE = 16;
  /** RegularExpression Id. */
  int ENDMODULE = 17;
  /** RegularExpression Id. */
  int BEGIN = 18;
  /** RegularExpression Id. */
  int END = 19;
  /** RegularExpression Id. */
  int FORK = 20;
  /** RegularExpression Id. */
  int JOIN = 21;
  /** RegularExpression Id. */
  int SPECIFY = 22;
  /** RegularExpression Id. */
  int ENDSPECIFY = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int FOREVER = 28;
  /** RegularExpression Id. */
  int REPEAT = 29;
  /** RegularExpression Id. */
  int WAIT = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int DEFAULT_LABEL = 32;
  /** RegularExpression Id. */
  int ENDCASE = 33;
  /** RegularExpression Id. */
  int FUNCTION = 34;
  /** RegularExpression Id. */
  int ENDFUNCTION = 35;
  /** RegularExpression Id. */
  int TASK = 36;
  /** RegularExpression Id. */
  int ENDTASK = 37;
  /** RegularExpression Id. */
  int GENERATE = 38;
  /** RegularExpression Id. */
  int ENDGENERATE = 39;
  /** RegularExpression Id. */
  int INPUT = 40;
  /** RegularExpression Id. */
  int OUTPUT = 41;
  /** RegularExpression Id. */
  int INOUT = 42;
  /** RegularExpression Id. */
  int INTEGER = 43;
  /** RegularExpression Id. */
  int REG = 44;
  /** RegularExpression Id. */
  int WIRE = 45;
  /** RegularExpression Id. */
  int EVENT = 46;
  /** RegularExpression Id. */
  int GENVAR = 47;
  /** RegularExpression Id. */
  int REAL = 48;
  /** RegularExpression Id. */
  int PARAMETER = 49;
  /** RegularExpression Id. */
  int LOCALPARAM = 50;
  /** RegularExpression Id. */
  int SIGNED = 51;
  /** RegularExpression Id. */
  int PROPERTY = 52;
  /** RegularExpression Id. */
  int ENDPROPERTY = 53;
  /** RegularExpression Id. */
  int ASSERT = 54;
  /** RegularExpression Id. */
  int ASSIGN = 55;
  /** RegularExpression Id. */
  int DEASSIGN = 56;
  /** RegularExpression Id. */
  int FORCE = 57;
  /** RegularExpression Id. */
  int RELEASE = 58;
  /** RegularExpression Id. */
  int TIME = 59;
  /** RegularExpression Id. */
  int REALTIME = 60;
  /** RegularExpression Id. */
  int DEFPARAM = 61;
  /** RegularExpression Id. */
  int OR = 62;
  /** RegularExpression Id. */
  int DISABLE = 63;
  /** RegularExpression Id. */
  int ALWAYS = 64;
  /** RegularExpression Id. */
  int INITIAL = 65;
  /** RegularExpression Id. */
  int EDGE = 66;
  /** RegularExpression Id. */
  int SUPPLY = 67;
  /** RegularExpression Id. */
  int NET_TYPE = 68;
  /** RegularExpression Id. */
  int STRENGTH = 69;
  /** RegularExpression Id. */
  int PRIM_1IN_XOUT = 70;
  /** RegularExpression Id. */
  int PRIM_1OUT_XIN = 71;
  /** RegularExpression Id. */
  int PRIM_1OUT_1IN_1CNTL = 72;
  /** RegularExpression Id. */
  int PRIM_1OUT = 73;
  /** RegularExpression Id. */
  int PRIM_1OUT_1IN_NC_PC = 74;
  /** RegularExpression Id. */
  int PRIM_BI = 75;
  /** RegularExpression Id. */
  int LPAREN = 76;
  /** RegularExpression Id. */
  int RPAREN = 77;
  /** RegularExpression Id. */
  int LBRACE = 78;
  /** RegularExpression Id. */
  int RBRACE = 79;
  /** RegularExpression Id. */
  int LBRACKET = 80;
  /** RegularExpression Id. */
  int RBRACKET = 81;
  /** RegularExpression Id. */
  int EOS = 82;
  /** RegularExpression Id. */
  int PARA = 83;
  /** RegularExpression Id. */
  int AT = 84;
  /** RegularExpression Id. */
  int DOLLAR = 85;
  /** RegularExpression Id. */
  int COMMA = 86;
  /** RegularExpression Id. */
  int DOT = 87;
  /** RegularExpression Id. */
  int AGN = 88;
  /** RegularExpression Id. */
  int GT = 89;
  /** RegularExpression Id. */
  int LT = 90;
  /** RegularExpression Id. */
  int BANG = 91;
  /** RegularExpression Id. */
  int TILDE = 92;
  /** RegularExpression Id. */
  int HOOK = 93;
  /** RegularExpression Id. */
  int COLON = 94;
  /** RegularExpression Id. */
  int PCOLON = 95;
  /** RegularExpression Id. */
  int MCOLON = 96;
  /** RegularExpression Id. */
  int EQ = 97;
  /** RegularExpression Id. */
  int LE = 98;
  /** RegularExpression Id. */
  int GE = 99;
  /** RegularExpression Id. */
  int NE = 100;
  /** RegularExpression Id. */
  int SC_OR = 101;
  /** RegularExpression Id. */
  int SC_AND = 102;
  /** RegularExpression Id. */
  int PLUS = 103;
  /** RegularExpression Id. */
  int MINUS = 104;
  /** RegularExpression Id. */
  int STAR = 105;
  /** RegularExpression Id. */
  int SLASH = 106;
  /** RegularExpression Id. */
  int BIT_AND = 107;
  /** RegularExpression Id. */
  int BIT_OR = 108;
  /** RegularExpression Id. */
  int XOR = 109;
  /** RegularExpression Id. */
  int REM = 110;
  /** RegularExpression Id. */
  int LSHIFT = 111;
  /** RegularExpression Id. */
  int RSHIFT = 112;
  /** RegularExpression Id. */
  int NEG_AND = 113;
  /** RegularExpression Id. */
  int NEG_OR = 114;
  /** RegularExpression Id. */
  int NEG_XOR = 115;
  /** RegularExpression Id. */
  int XOR_NEG = 116;
  /** RegularExpression Id. */
  int EQ_C = 117;
  /** RegularExpression Id. */
  int NE_C = 118;
  /** RegularExpression Id. */
  int POWER = 119;
  /** RegularExpression Id. */
  int ALSHIFT = 120;
  /** RegularExpression Id. */
  int ARSHIFT = 121;
  /** RegularExpression Id. */
  int IDENT = 122;
  /** RegularExpression Id. */
  int SYSTEM_IDENT = 123;
  /** RegularExpression Id. */
  int LETTER = 124;
  /** RegularExpression Id. */
  int BACKSLASH = 125;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 126;
  /** RegularExpression Id. */
  int NUMBER_LITERAL = 127;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 128;
  /** RegularExpression Id. */
  int HEX_LITERAL = 129;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 130;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 131;
  /** RegularExpression Id. */
  int REAL_LITERAL = 132;
  /** RegularExpression Id. */
  int STRING_LITERAL = 133;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_PROPERTY = 2;
  /** Lexical state. */
  int IN_PROTECTED = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"*)\"",
    "<token of kind 6>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "<token of kind 12>",
    "<PROTECTED>",
    "<token of kind 14>",
    "<SINGLE_LINE_COMMENT>",
    "\"module\"",
    "\"endmodule\"",
    "\"begin\"",
    "\"end\"",
    "\"fork\"",
    "\"join\"",
    "\"specify\"",
    "\"endspecify\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"forever\"",
    "\"repeat\"",
    "\"wait\"",
    "<CASE>",
    "\"default\"",
    "\"endcase\"",
    "\"function\"",
    "\"endfunction\"",
    "\"task\"",
    "\"endtask\"",
    "\"generate\"",
    "\"endgenerate\"",
    "\"input\"",
    "\"output\"",
    "\"inout\"",
    "\"integer\"",
    "\"reg\"",
    "\"wire\"",
    "\"event\"",
    "\"genvar\"",
    "\"real\"",
    "\"parameter\"",
    "\"localparam\"",
    "\"signed\"",
    "\"property\"",
    "\"endproperty\"",
    "<ASSERT>",
    "\"assign\"",
    "\"deassign\"",
    "\"force\"",
    "\"release\"",
    "\"time\"",
    "\"realtime\"",
    "\"defparam\"",
    "\"or\"",
    "\"disable\"",
    "\"always\"",
    "\"initial\"",
    "<EDGE>",
    "<SUPPLY>",
    "<NET_TYPE>",
    "<STRENGTH>",
    "<PRIM_1IN_XOUT>",
    "<PRIM_1OUT_XIN>",
    "<PRIM_1OUT_1IN_1CNTL>",
    "<PRIM_1OUT>",
    "<PRIM_1OUT_1IN_NC_PC>",
    "<PRIM_BI>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"#\"",
    "\"@\"",
    "\"$\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"+:\"",
    "\"-:\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\"~&\"",
    "\"~|\"",
    "\"~^\"",
    "\"^~\"",
    "\"===\"",
    "\"!==\"",
    "\"**\"",
    "\"<<<\"",
    "\">>>\"",
    "<IDENT>",
    "<SYSTEM_IDENT>",
    "<LETTER>",
    "\"\\\\\"",
    "<INTEGER_LITERAL>",
    "<NUMBER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<BINARY_LITERAL>",
    "<REAL_LITERAL>",
    "<STRING_LITERAL>",
    "\"->\"",
  };

}
