/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;



/* Generated By:JJTree: Do not edit this line. ASTarchitecture_body.java */
/* JJT: 0.3pre1 */

public class ASTarchitecture_body extends SimpleNode {
  ASTarchitecture_body(int id) {
    super(id);
  }


  public String getIdentifier(){
	  return ((ASTidentifier)jjtGetChild(0)).name;
  }
  
  public String getEntityName(){
	  ASTname astName=(ASTname)getChild(1);
	  return ((ASTidentifier)(astName.jjtGetChild(0))).name;
  }

  /**
   * semantic-checks for architecture_body:
   * - identifiers at beginning and end must match.
   * - entity_name denotes an entity.
   */
  public void Check()
  {
    // identifiers at beginning and end must match
    String s1 = ((ASTidentifier)jjtGetChild(0)).name;

    int i = jjtGetNumChildren()-1;
    if (jjtGetChild(i).toString() == "identifier")
    {
      if ( s1.compareToIgnoreCase( ((ASTidentifier)jjtGetChild(i)).name) != 0)
        getErrorHandler().Error("identifiers don't match: "
          +s1+"/="+((ASTidentifier)jjtGetChild(i)).name,null);
    }


    // the entity_name denotes an entity
    // to be done (name must be done before...)

    CheckSIWGLevel1();
  }



}
