/* Generated By:JJTree: Do not edit this line. ASTbare_range.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTbare_range extends SimpleNode {
  public ASTbare_range(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=fcfeed3dd48ab1724c496a21d317a685 (do not edit this line) */
