/* Generated By:JJTree: Do not edit this line. ASTcase_generate_statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTcase_generate_statement extends SimpleNode {
  public ASTcase_generate_statement(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=7512e8118b8f3eee00d7aca9ac9d12f1 (do not edit this line) */
