/* Generated By:JJTree: Do not edit this line. ASTcase_generate_alternative.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTcase_generate_alternative extends SimpleNode {
  public ASTcase_generate_alternative(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=ebe7c3dac841b7d7e410591e077e71d2 (do not edit this line) */
