/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;

/* Generated By:JJTree: Do not edit this line. ASTcase_statement_alternative.java */
/* JJT: 0.3pre1 */

public class ASTcase_statement_alternative extends SimpleNode {
	ASTcase_statement_alternative(int id) {
		super(id);
	}

	@Override
	public void jjtOpen() {	
		super.jjtOpen();
	}

	@Override
	public void jjtClose() {	
		super.jjtClose();
	}
}
