/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;



/* Generated By:JJTree: Do not edit this line. ASTformal_parameter_list.java */
/* JJT: 0.3pre1 */

public class ASTformal_parameter_list extends SimpleNode {
  ASTformal_parameter_list(int id) {
    super(id);
  }
  
  public ASTinterface_list getInterfaceList(){
	  for(Node child:children){
		  if(child instanceof ASTinterface_list)
			  return (ASTinterface_list)child; 
	  }
	  return null;
  }
}
