/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;



/* Generated By:JJTree: Do not edit this line. ASTfile_open_information.java */
/* JJT: 0.3pre1 */

public class ASTfile_open_information extends SimpleNode {
  ASTfile_open_information(int id) {
    super(id);
  }
}
