/* Generated By:JJTree: Do not edit this line. ASTif_generate_statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTif_generate_statement extends SimpleNode {
  public ASTif_generate_statement(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=82a2dcdb419dfc624864d5015bc2336d (do not edit this line) */
