/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;



/* Generated By:JJTree: Do not edit this line. ASTidentifier.java */
/* JJT: 0.3pre1 */

public class ASTidentifier extends SimpleNode {
  ASTidentifier(int id) {
    super(id);
  }
  String name;
}
