/* Generated By:JJTree: Do not edit this line. ASTpackage_instantiation_declaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTpackage_instantiation_declaration extends SimpleNode {
  public ASTpackage_instantiation_declaration(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=290e7eae4da2eee7630c16866f39c572 (do not edit this line) */
