/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;



/* Generated By:JJTree: Do not edit this line. ASTrecord_type_definition.java */
/* JJT: 0.3pre1 */

public class ASTrecord_type_definition extends SimpleNode {
  ASTrecord_type_definition(int id) {
    super(id);
  }
}
