/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;



/* Generated By:JJTree: Do not edit this line. ASTsubprogram_body.java */
/* JJT: 0.3pre1 */

public class ASTsubprogram_body extends SimpleNode {
  ASTsubprogram_body(int id) {
    super(id);
  }
  
  ASTsubprogram_specification getSpecification(){
	  return (ASTsubprogram_specification)getChild(0);
  }
}
