/**
 * 
 * This file is based on the VHDL parser originally developed by
 * (c) 1997 Christoph Grimm,
 * J.W. Goethe-University Frankfurt
 * Department for computer engineering
 *
 **/
package net.sourceforge.veditor.parser.vhdl;

/* Generated By:JJTree: Do not edit this line. ASTvariable_declaration.java */
/* JJT: 0.3pre1 */

public class ASTvariable_declaration extends SimpleNode {
	ASTvariable_declaration(int id) {
		super(id);
	}

	@Override
	public void jjtOpen() {
		// TODO Auto-generated method stub
		super.jjtOpen();
	}

	@Override
	public void jjtClose() {
		// TODO Auto-generated method stub
		super.jjtClose();
	}

	public String[] getIdentifierList() {
		return ((ASTidentifier_list) jjtGetChild(0)).getIdentifierNames();
	}

	public String getSubType() {
		ASTsubtype_indication subtype = (ASTsubtype_indication) jjtGetChild(1);
		return subtype.getIdentifier();
	}
}
