/* Generated By:JJTree: Do not edit this line. C:\home\work\veditor\src\net\sourceforge\veditor\parser\vhdl\VhdlParserCoreTreeConstants.java */

package net.sourceforge.veditor.parser.vhdl;

public interface VhdlParserCoreTreeConstants
{
  public int JJTVOID = 0;
  public int JJTACTUAL_PART = 1;
  public int JJTAGGREGATE = 2;
  public int JJTALIAS_DECLARATION = 3;
  public int JJTALIAS_DESIGNATOR = 4;
  public int JJTALLOCATOR = 5;
  public int JJTARCHITECTURE_BODY = 6;
  public int JJTARCHITECTURE_DECLARATIVE_PART = 7;
  public int JJTARCHITECTURE_STATEMENT_PART = 8;
  public int JJTUNCONSTRAINED_NATURE_DEFINITION = 9;
  public int JJTCONSTRAINED_NATURE_DEFINITION = 10;
  public int JJTASSERTION = 11;
  public int JJTASSERTION_STATEMENT = 12;
  public int JJTASSOCIATION_ELEMENT = 13;
  public int JJTASSOCIATION_LIST = 14;
  public int JJTATTRIBUTE_DECLARATION = 15;
  public int JJTATTRIBUTE_NAME = 16;
  public int JJTATTRIBUTE_SPECIFICATION = 17;
  public int JJTBINDING_INDICATION = 18;
  public int JJTBLOCK_CONFIGURATION = 19;
  public int JJTBLOCK_DECLARATIVE_PART = 20;
  public int JJTBLOCK_HEADER = 21;
  public int JJTBLOCK_SPECIFICATION = 22;
  public int JJTBLOCK_STATEMENT = 23;
  public int JJTBLOCK_STATEMENT_PART = 24;
  public int JJTBREAK_STATEMENT = 25;
  public int JJTBREAK_LIST = 26;
  public int JJTBREAK_ELEMENT = 27;
  public int JJTCASE_STATEMENT = 28;
  public int JJTCASE_STATEMENT_ALTERNATIVE = 29;
  public int JJTCHOICE = 30;
  public int JJTCHOICES = 31;
  public int JJTCOMPONENT_CONFIGURATION = 32;
  public int JJTCOMPONENT_DECLARATION = 33;
  public int JJTCOMPONENT_INSTANTIATION_STATEMENT = 34;
  public int JJTCOMPONENT_SPECIFICATION = 35;
  public int JJTCOMPOSITE_TYPE_DEFINITION = 36;
  public int JJTCONCURRENT_ASSERTION_STATEMENT = 37;
  public int JJTCONCURRENT_PROCEDURE_CALL_STATEMENT = 38;
  public int JJTCONCURRENT_SIGNAL_ASSIGNMENT_STATEMENT = 39;
  public int JJTCONDITIONAL_SIGNAL_ASSIGNMENT = 40;
  public int JJTCONDITIONAL_WAVEFORMS = 41;
  public int JJTCONFIGURATION_DECLARATION = 42;
  public int JJTCONFIGURATION_DECLARATIVE_PART = 43;
  public int JJTCONFIGURATION_SPECIFICATION = 44;
  public int JJTCONSTANT_DECLARATION = 45;
  public int JJTCONSTRAINED_ARRAY_DEFINITION = 46;
  public int JJTCONTEXT_CLAUSE = 47;
  public int JJTTERMINAL_DECLARATION = 48;
  public int JJTTERMINAL_ASPECT = 49;
  public int JJTDELAY_MECHANISM = 50;
  public int JJTDESIGN_FILE = 51;
  public int JJTDESIGN_UNIT = 52;
  public int JJTDIRECTION = 53;
  public int JJTDISCONNECTION_SPECIFICATION = 54;
  public int JJTELEMENT_DECLARATION = 55;
  public int JJTENTITY_ASPECT = 56;
  public int JJTENTITY_CLASS_ENTRY = 57;
  public int JJTENTITY_CLASS_ENTRY_LIST = 58;
  public int JJTENTITY_DECLARATION = 59;
  public int JJTNATURE_DECLARATION = 60;
  public int JJTSUBNATURE_DECLARATION = 61;
  public int JJTSUBNATURE_INDICATION = 62;
  public int JJTENTITY_DECLARATIVE_PART = 63;
  public int JJTENTITY_DESIGNATOR = 64;
  public int JJTENTITY_HEADER = 65;
  public int JJTENTITY_NAME_LIST = 66;
  public int JJTENTITY_SPECIFICATION = 67;
  public int JJTENTITY_STATEMENT_PART = 68;
  public int JJTENTITY_TAG = 69;
  public int JJTENUMERATION_LITERAL = 70;
  public int JJTENUMERATION_TYPE_DEFINITION = 71;
  public int JJTEXIT_STATEMENT = 72;
  public int JJTRELATION = 73;
  public int JJTFACTOR = 74;
  public int JJTFILE_DECLARATION = 75;
  public int JJTFILE_OPEN_INFORMATION = 76;
  public int JJTFORMAL_PARAMETER_LIST = 77;
  public int JJTFULL_TYPE_DECLARATION = 78;
  public int JJTFUNCTION_CALL = 79;
  public int JJTGENERATE_STATEMENT = 80;
  public int JJTCONCURRENT_BREAK_STATEMENT = 81;
  public int JJTGENERATION_SCHEME = 82;
  public int JJTGENERIC_CLAUSE = 83;
  public int JJTGROUP_CONSTITUENT = 84;
  public int JJTGROUP_CONSTITUENT_LIST = 85;
  public int JJTGROUP_TEMPLATE_DECLARATION = 86;
  public int JJTGROUP_DECLARATION = 87;
  public int JJTGUARDED_SIGNAL_SPECIFICATION = 88;
  public int JJTIDENTIFIER = 89;
  public int JJTIDENTIFIER_LIST = 90;
  public int JJTIF_STATEMENT = 91;
  public int JJTINCOMPLETE_TYPE_DECLARATION = 92;
  public int JJTINDEX_CONSTRAINT = 93;
  public int JJTINDEX_SPECIFICATION = 94;
  public int JJTINDEX_SUBTYPE_DEFINITION = 95;
  public int JJTINDEXED_NAME = 96;
  public int JJTINSTANTIATED_UNIT = 97;
  public int JJTINSTANTIATION_LIST = 98;
  public int JJTINTERFACE_CONSTANT_DECLARATION = 99;
  public int JJTINTERFACE_TERMINAL_DECLARATION = 100;
  public int JJTINTERFACE_QUANTITY_DECLARATION = 101;
  public int JJTINTERFACE_FILE_DECLARATION = 102;
  public int JJTINTERFACE_LIST = 103;
  public int JJTINTERFACE_SIGNAL_DECLARATION = 104;
  public int JJTINTERFACE_VARIABLE_DECLARATION = 105;
  public int JJTITERATION_SCHEME = 106;
  public int JJTLITERAL = 107;
  public int JJTLOGICAL_NAME_LIST = 108;
  public int JJTLOOP_STATEMENT = 109;
  public int JJTMODE = 110;
  public int JJTNAME = 111;
  public int JJTNATURE_ELEMENT_DECLARATION = 112;
  public int JJTNEXT_STATEMENT = 113;
  public int JJTNULL_STATEMENT = 114;
  public int JJTOPERATOR_SYMBOL = 115;
  public int JJTOPTIONS_ = 116;
  public int JJTPACKAGE_BODY = 117;
  public int JJTPACKAGE_BODY_DECLARATIVE_PART = 118;
  public int JJTPACKAGE_DECLARATION = 119;
  public int JJTPACKAGE_DECLARATIVE_PART = 120;
  public int JJTPARAMETER_SPECIFICATION = 121;
  public int JJTPHYSICAL_LITERAL = 122;
  public int JJTPHYSICAL_TYPE_DEFINITION = 123;
  public int JJTPORT_CLAUSE = 124;
  public int JJTPORT_MAP_ASPECT = 125;
  public int JJTPREFIX = 126;
  public int JJTPROCEDURE_CALL = 127;
  public int JJTPROCEDURE_CALL_STATEMENT = 128;
  public int JJTPROCESS_DECLARATIVE_PART = 129;
  public int JJTPROCESS_STATEMENT = 130;
  public int JJTPROCESS_STATEMENT_PART = 131;
  public int JJTQUALIFIED_EXPRESSION = 132;
  public int JJTRANGE = 133;
  public int JJTRECORD_NATURE_DEFINITION = 134;
  public int JJTRECORD_TYPE_DEFINITION = 135;
  public int JJTSHIFT_EXPRESSION = 136;
  public int JJTREPORT_STATEMENT = 137;
  public int JJTRETURN_STATEMENT = 138;
  public int JJTSCALAR_NATURE_DEFINITION = 139;
  public int JJTSECONDARY_UNIT_DECLARATION = 140;
  public int JJTSELECTED_NAME = 141;
  public int JJTSELECTED_SIGNAL_ASSIGNMENT = 142;
  public int JJTSELECTED_WAVEFORMS = 143;
  public int JJTSENSITIVITY_LIST = 144;
  public int JJTSEQUENCE_OF_STATEMENTS = 145;
  public int JJTSIMPLE_EXPRESSION = 146;
  public int JJTSIGN = 147;
  public int JJTSIGNAL_ASSIGNMENT_STATEMENT = 148;
  public int JJTSIGNAL_DECLARATION = 149;
  public int JJTSIGNAL_KIND = 150;
  public int JJTSIGNAL_LIST = 151;
  public int JJTSIGNATURE = 152;
  public int JJTTERM = 153;
  public int JJTSLICE_NAME = 154;
  public int JJTSUBPROGRAM_BODY = 155;
  public int JJTSUBPROGRAM_DECLARATIVE_PART = 156;
  public int JJTSUBPROGRAM_SPECIFICATION = 157;
  public int JJTSUBPROGRAM_STATEMENT_PART = 158;
  public int JJTSUBTYPE_DECLARATION = 159;
  public int JJTSUBTYPE_INDICATION = 160;
  public int JJTFREE_QUANTITY_DECLARATION = 161;
  public int JJTBRANCH_QUANTITY_DECLARATION = 162;
  public int JJTSOURCE_QUANTITY_DECLARATION = 163;
  public int JJTACROSS_ASPECT = 164;
  public int JJTTHROUGH_ASPECT = 165;
  public int JJTSOURCE_ASPECT = 166;
  public int JJTTYPE_CONVERSION = 167;
  public int JJTUNCONSTRAINED_ARRAY_DEFINITION = 168;
  public int JJTUSE_CLAUSE = 169;
  public int JJTVARIABLE_ASSIGNMENT_STATEMENT = 170;
  public int JJTVARIABLE_DECLARATION = 171;
  public int JJTWAIT_STATEMENT = 172;
  public int JJTWAVEFORM = 173;
  public int JJTWAVEFORM_ELEMENT = 174;
  public int JJTSIMULTANEOUS_STATEMENT_PART = 175;
  public int JJTSIMPLE_SIMULTANEOUS_STATEMENT = 176;
  public int JJTSIMULTANEOUS_IF_STATEMENT = 177;
  public int JJTSIMULTANEOUS_CASE_STATEMENT = 178;
  public int JJTSIMULTANEOUS_ALTERNATIVE = 179;
  public int JJTSIMULTANEOUS_PROCEDURAL_STATEMENT = 180;
  public int JJTPROCEDURAL_DECLARATIVE_PART = 181;
  public int JJTPROCEDURAL_STATEMENT_PART = 182;
  public int JJTSIMULTANEOUS_NULL_STATEMENT = 183;
  public int JJTSHARED_VARIABLE_DECLARATION = 184;
  public int JJTERROR_SKIPTO = 185;


  public String[] jjtNodeName = {
    "void",
    "actual_part",
    "aggregate",
    "alias_declaration",
    "alias_designator",
    "allocator",
    "architecture_body",
    "architecture_declarative_part",
    "architecture_statement_part",
    "unconstrained_nature_definition",
    "constrained_nature_definition",
    "assertion",
    "assertion_statement",
    "association_element",
    "association_list",
    "attribute_declaration",
    "attribute_name",
    "attribute_specification",
    "binding_indication",
    "block_configuration",
    "block_declarative_part",
    "block_header",
    "block_specification",
    "block_statement",
    "block_statement_part",
    "break_statement",
    "break_list",
    "break_element",
    "case_statement",
    "case_statement_alternative",
    "choice",
    "choices",
    "component_configuration",
    "component_declaration",
    "component_instantiation_statement",
    "component_specification",
    "composite_type_definition",
    "concurrent_assertion_statement",
    "concurrent_procedure_call_statement",
    "concurrent_signal_assignment_statement",
    "conditional_signal_assignment",
    "conditional_waveforms",
    "configuration_declaration",
    "configuration_declarative_part",
    "configuration_specification",
    "constant_declaration",
    "constrained_array_definition",
    "context_clause",
    "terminal_declaration",
    "terminal_aspect",
    "delay_mechanism",
    "design_file",
    "design_unit",
    "direction",
    "disconnection_specification",
    "element_declaration",
    "entity_aspect",
    "entity_class_entry",
    "entity_class_entry_list",
    "entity_declaration",
    "nature_declaration",
    "subnature_declaration",
    "subnature_indication",
    "entity_declarative_part",
    "entity_designator",
    "entity_header",
    "entity_name_list",
    "entity_specification",
    "entity_statement_part",
    "entity_tag",
    "enumeration_literal",
    "enumeration_type_definition",
    "exit_statement",
    "relation",
    "factor",
    "file_declaration",
    "file_open_information",
    "formal_parameter_list",
    "full_type_declaration",
    "function_call",
    "generate_statement",
    "concurrent_break_statement",
    "generation_scheme",
    "generic_clause",
    "group_constituent",
    "group_constituent_list",
    "group_template_declaration",
    "group_declaration",
    "guarded_signal_specification",
    "identifier",
    "identifier_list",
    "if_statement",
    "incomplete_type_declaration",
    "index_constraint",
    "index_specification",
    "index_subtype_definition",
    "indexed_name",
    "instantiated_unit",
    "instantiation_list",
    "interface_constant_declaration",
    "interface_terminal_declaration",
    "interface_quantity_declaration",
    "interface_file_declaration",
    "interface_list",
    "interface_signal_declaration",
    "interface_variable_declaration",
    "iteration_scheme",
    "literal",
    "logical_name_list",
    "loop_statement",
    "mode",
    "name",
    "nature_element_declaration",
    "next_statement",
    "null_statement",
    "operator_symbol",
    "options_",
    "package_body",
    "package_body_declarative_part",
    "package_declaration",
    "package_declarative_part",
    "parameter_specification",
    "physical_literal",
    "physical_type_definition",
    "port_clause",
    "port_map_aspect",
    "prefix",
    "procedure_call",
    "procedure_call_statement",
    "process_declarative_part",
    "process_statement",
    "process_statement_part",
    "qualified_expression",
    "range",
    "record_nature_definition",
    "record_type_definition",
    "shift_expression",
    "report_statement",
    "return_statement",
    "scalar_nature_definition",
    "secondary_unit_declaration",
    "selected_name",
    "selected_signal_assignment",
    "selected_waveforms",
    "sensitivity_list",
    "sequence_of_statements",
    "simple_expression",
    "sign",
    "signal_assignment_statement",
    "signal_declaration",
    "signal_kind",
    "signal_list",
    "signature",
    "term",
    "slice_name",
    "subprogram_body",
    "subprogram_declarative_part",
    "subprogram_specification",
    "subprogram_statement_part",
    "subtype_declaration",
    "subtype_indication",
    "free_quantity_declaration",
    "branch_quantity_declaration",
    "source_quantity_declaration",
    "across_aspect",
    "through_aspect",
    "source_aspect",
    "type_conversion",
    "unconstrained_array_definition",
    "use_clause",
    "variable_assignment_statement",
    "variable_declaration",
    "wait_statement",
    "waveform",
    "waveform_element",
    "simultaneous_statement_part",
    "simple_simultaneous_statement",
    "simultaneous_if_statement",
    "simultaneous_case_statement",
    "simultaneous_alternative",
    "simultaneous_procedural_statement",
    "procedural_declarative_part",
    "procedural_statement_part",
    "simultaneous_null_statement",
    "shared_variable_declaration",
    "error_skipto",
  };
}
